#!/bin/bash

pwd

cd /var/lib/jenkins
pwd

#ssh ubuntu@65.2.132.44 << EOF
#	ls
#	cd to_do_app/
#
#EOF

#ssh ubuntu@65.2.132.44 './deploy_code'

echo "Jenkins@admin" | sudo -S ssh -i "bharat-aws.pem" ubuntu@65.2.132.44
